name: care_v1
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - ase=3.22.1
  - atk-1.0=2.38.0
  - blas=1.0
  - blinker=1.6.3
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.18.0
  - certifi=2023.7.22
  - charset-normalizer=3.3.1
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.1.1
  - cpuonly=2.0
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.5.0
  - ffmpeg=6.0.0
  - filelock=3.12.4
  - flask=3.0.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - graphite2=1.3.13
  - graphviz=8.1.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=8.2.1
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.3.2
  - kiwisolver=1.4.5
  - lame=3.100
  - latexcodec=2.0.1
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libass=0.17.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.19
  - libdrm=2.4.114
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgd=2.3.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libpciaccess=0.17
  - libpng=1.6.39
  - librsvg=2.56.3
  - libsqlite=3.43.2
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libtool=2.4.7
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.20.0
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=8.0.1
  - markupsafe=2.1.3
  - matplotlib-base=3.8.0
  - mkl=2023.1.0
  - monty=2023.9.25
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.8.1
  - networkx=3.2
  - numpy=1.26.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.3
  - p11-kit=0.24.1
  - packaging=23.2
  - palettable=3.3.3
  - pandas=2.1.1
  - pango=1.50.14
  - pcre2=10.40
  - pillow=10.1.0
  - pip=23.3.1
  - pixman=0.42.2
  - plotly=5.17.0
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pybtex=0.24.0
  - pydot=1.4.2
  - pyg=2.4.0
  - pymatgen=2023.10.11
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.0
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.18.1
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - setuptools=68.2.2
  - six=1.16.0
  - spglib=2.1.0
  - svt-av1=1.7.0
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.10.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tk=8.6.13
  - torchaudio=2.1.0
  - torchvision=0.16.0
  - tqdm=4.66.1
  - typing_extensions=4.8.0
  - tzdata=2023c
  - uncertainties=3.1.7
  - urllib3=2.0.7
  - werkzeug=3.0.0
  - wheel=0.41.2
  - x264=1!164.3095
  - x265=3.5
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - acat==1.6.8
      - energydiagram==0.2.0
      - pubchempy==1.0.4
      - rdkit==2023.3.3
