name: care
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - ase=3.22.1
  - blas=2.117
  - blas-devel=3.9.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.6
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - emmet-core=0.64.4
  - filelock=3.9.0
  - flask=2.3.2
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozendict=2.3.8
  - future=0.18.3
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - latexcodec=2.0.1
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.7.1
  - monty=2023.8.8
  - mp-api=0.33.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openblas=0.3.23
  - openssl=3.1.2
  - packaging=23.1
  - palettable=3.3.3
  - pandas=2.0.3
  - pillow=9.4.0
  - pip=23.2.1
  - plotly=5.16.0
  - pubchempy=1.0.4
  - pybtex=0.24.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pymatgen=2023.8.10
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytorch=2.0.1
  - pytz=2023.3
  - pyyaml=6.0
  - readline=8.2
  - requests=2.31.0
  - ruamel.yaml=0.17.32
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - setuptools=68.0.0
  - six=1.16.0
  - spglib=2.0.2
  - sqlite=3.41.2
  - sympy=1.11.1
  - tabulate=0.9.0
  - tenacity=8.2.2
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - tqdm=4.66.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzdata=2023c
  - uncertainties=3.1.7
  - urllib3=1.26.16
  - werkzeug=2.3.6
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - psutil==5.9.5
      - rdkit==2023.3.2
      - torch-geometric==2.3.1
