[chemspace]
ncc = 1 # Network Carbon Cutoff (int)
noc = 2  # Network Oxygen Cutoff (int, if <0, maximum O saturation)
regen = true #Force the re-generatation of the existing CRN (bool)
additional = true #Include 1.2-H shifts (bool)
electro = false #ochemical process, readjusts the reaction expressions accordingly (bool)
cyclic = false

[surface]
metal = "Fe" # metal catalyst (str)
hkl = "110" # Surface facet, fcc/bcc metals: "111", "110" "100"; hcp metals: "0001", "10m10","10m11" (str)

[evaluator]
model = "ocp"  # available are gamenetuq, ocp, mace
name = "EquiformerV2-31M-S2EF-OC20-All+MD" # Model name (check available ones on fairchem repo :))
device = "cpu"  # Device (cpu/cuda)
fmax = 0.05  # Convergence criterion: if fmax lower than fmax, stop relaxation
max_steps = 100  # Max number of ionic steps
num_configs = 3  # Number of adsorption configurations per adsorbate-surface pair to screen
