[chemspace]
ncc = 1  # Network Carbon Cutoff
noc = 4 # Network Oxygen Cutoff (if negative value, maximum number of Os added)
regen = true  # Force the re-generatation of the existing CRN
additional = true  # Consider additional reactions (i.e., 1.2-H shifts)

[surface]
metal = "Pt"  # Catalyst
hkl = "111"  # Surface facet


[mkm]
run = true  # Run microkinetic simulation


[reactor]
type = "DifferentialPFR"  # Reactor type. Available: "DynamicCSTR", "DifferentialPFR"
electro = false  # Electrochemical process


[operating_conditions]
temperature = 574  # K
pressure = 102730  # Pa
radius = 0.0175  # m
length = 0.01  # m
Q = 0.01  # m^3/s
m_cat = 0.005  # kg
s_bet = 10E5  # m^2/kg_cat


[initial_conditions]
# CH2O2 = 0.0261  # Molar fraction of inlet gas
# CO2 = 0.1461
# CH4O = 0.028
# He = 0.972  # Molar fraction of inlet gas
N2 = 0.9
CH4O = 0.1
