[chemspace]
ncc = 3 # Network Carbon Cutoff (int)
noc = 3 # Network Oxygen Cutoff (int, if <0, maximum O saturation)
regen = false  # Force the re-generatation of the existing CRN (bool)
additional = false  # Include 1.2-H shifts (bool)
electro = true # Electrochemical process, readjusts the reaction expressions accordingly (bool)


[surface]
metal = "Cu"  # metal catalyst (str)
hkl = "100"  # Surface facet, fcc/bcc metals: "111", "110" "100"; hcp metals: "0001", "10m10","10m11" (str)


[mkm]
run = true # Run microkinetic simulation (bool)
solver = "Julia" # "Python" for Scipy BDF or "Julia" to run with DifferentialEquations.jl on CPU/GPU (str)
barrier_threshold = 2.0  # filter out elementary reactions whose activation barriers (both direct and reverse) are higher than this value (None or float)
uq = false  # Uncertainty quantification (bool)
uq_samples = 100  # Number of samples to get for the UQ (int)
thermo = false  # If true, the activation barriers are neglected and only the thermodynamic path is considered (bool) 


[operating_conditions]
temperature = 298 # temperature in Kelvin (float)
pressure = 1E05  # total pressure in Pascal (float)
pH = 8 # pH, used only when electro is true (float between 1 and 14)
U = -1.5 # applied potential in Volt, used only when electro is true (float)


[initial_conditions] # molar fractions of the species of the gas mixture the reactor is exposed to, total sum must be 1!
CO2 = 1.0 
