name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v' (e.g., v0.1.4)

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools_scm

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
